name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs: 
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out the code
        uses: actions/checkout@v2
#       - name: Step 2 - run commands
#         run: pwd
      - name: Step 3 - Upload the artifact 
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

